name: ds
channels:
- pytorch
# - huggingface
# - fastai
# - conda-forge
dependencies:
- python=3.10
- pytorch>=2
- transformers
- numpy
- scipy
- pandas
- matplotlib
- seaborn
- execnb
- conda-forge/label/jupyterlab_alpha::jupyterlab
- ipywidgets
- pip:
  - jupyterlab_rise
