name: ds
channels:
- pytorch
# - huggingface
# - fastai
# - conda-forge
dependencies:
- python=3.10
- pytorch>=2
- transformers
- numpy
- scipy
- pandas>=2
- matplotlib
- seaborn
- execnb
- jupyterlab>=4
- ipywidgets
- pandoc
- nbconvert[webpdf]
# - pip:
#   - jupyterlab_rise
