name: ds
channels:
# - pytorch
# - huggingface
# - fastai
# - conda-forge
dependencies:
- pytorch
- transformers
- numpy
- scipy
- pandas
- matplotlib
- seaborn
- execnb
- conda-forge/label/jupyterlab_alpha::jupyterlab
- ipywidgets
- pip:
  - jupyterlab_rise
